language: ruby

rvm:
  - ruby-head
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - rbx-2
  - rbx
  - 1.9.3
  - jruby-head
  - jruby-19mode

script: bundle exec rspec spec

sudo: false

env:
  matrix:
    - "TASK=benchmark"

matrix:
  allow_failures:
    # - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx
    - rvm: rbx-2
