# Include Opulent nodes which know how to evaluate themselves
require_relative 'nodes/helper'
require_relative 'nodes/root'
require_relative 'nodes/node'
require_relative 'nodes/define'
require_relative 'nodes/eval'
require_relative 'nodes/expression'
require_relative 'nodes/text'
require_relative 'nodes/filter'
require_relative 'nodes/control'
require_relative 'nodes/theme'
require_relative 'nodes/block'
require_relative 'nodes/comment'
